//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUILDING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BUILDING()
        {
            this.ROOMS = new HashSet<ROOM>();
        }
    
        public string ORIGSTS { get; set; }
        public int ORIGREC { get; set; }
        public string DESCRIPTION { get; set; }
        public string DEPT { get; set; }
        public string BUILDING_NAME { get; set; }
        public int BUILDING_ID { get; set; }
        public string BUILDING_CODE { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROOM> ROOMS { get; set; }
    }
}
