//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_PHYSICAL_INVENTORY_REV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMS_PHYSICAL_INVENTORY_REV()
        {
            this.IMS_PHYSICAL_INVENTORY = new HashSet<IMS_PHYSICAL_INVENTORY>();
        }
    
        public int ORIGREC { get; set; }
        public string ORIGSTS { get; set; }
        public int PHYSICALINVENTORYREVIEWID { get; set; }
        public string NAME { get; set; }
        public System.DateTime START_TIME { get; set; }
        public Nullable<System.DateTime> END_TIME { get; set; }
        public string USRNAM { get; set; }
        public string STATUS { get; set; }
        public string TEXT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_PHYSICAL_INVENTORY> IMS_PHYSICAL_INVENTORY { get; set; }
    }
}
