//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_PRODUCTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMS_PRODUCTS()
        {
            this.IMS_ITEMS = new HashSet<IMS_ITEMS>();
            this.IMS_LOTS = new HashSet<IMS_LOTS>();
            this.IMS_COST_CENTER_PRODUCTS = new HashSet<IMS_COST_CENTER_PRODUCTS>();
            this.IMS_COST_CENTER_PRODUCTS1 = new HashSet<IMS_COST_CENTER_PRODUCTS>();
            this.IMS_PO_LINE_ITEMS = new HashSet<IMS_PO_LINE_ITEMS>();
            this.IMS_PO_LINE_ITEMS1 = new HashSet<IMS_PO_LINE_ITEMS>();
            this.IMS_SHIPMENT_LINE_ITEMS = new HashSet<IMS_SHIPMENT_LINE_ITEMS>();
        }
    
        public int ORIGREC { get; set; }
        public string ORIGSTS { get; set; }
        public int PRODUCTID { get; set; }
        public string LISTNUMBER { get; set; }
        public string GTIN { get; set; }
        public string STATUS { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string TYPE { get; set; }
        public decimal QUANTITY { get; set; }
        public string UNIT { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string STORAGE_CONDITION { get; set; }
        public string HAS_LOTS { get; set; }
        public string HAS_EXPIRY_DATE { get; set; }
        public string IS_RFID_TAGGED { get; set; }
        public string IS_ORDERABLE { get; set; }
        public string IS_VIRTUAL { get; set; }
        public string SUPPCODE { get; set; }
        public string OLD_LISTNUMBER { get; set; }
        public string NEW_LISTNUMBER { get; set; }
        public string COMPANY_PREFIX { get; set; }
        public string IS_EDITABLE { get; set; }
        public string CUSTOMERMATERIALID { get; set; }
        public string CUSTOMERMATERIALGROUP { get; set; }
        public string SHORT_NAME { get; set; }
        public string IS_NON_CANON { get; set; }
        public string ERP_KEY_DATA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_ITEMS> IMS_ITEMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_LOTS> IMS_LOTS { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
        public virtual SUPPLIER SUPPLIER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_COST_CENTER_PRODUCTS> IMS_COST_CENTER_PRODUCTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_COST_CENTER_PRODUCTS> IMS_COST_CENTER_PRODUCTS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_PO_LINE_ITEMS> IMS_PO_LINE_ITEMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_PO_LINE_ITEMS> IMS_PO_LINE_ITEMS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_SHIPMENT_LINE_ITEMS> IMS_SHIPMENT_LINE_ITEMS { get; set; }
    }
}
