//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_SHIPMENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMS_SHIPMENTS()
        {
            this.IMS_PO_SHIPMENTS = new HashSet<IMS_PO_SHIPMENTS>();
            this.IMS_SHIPMENT_LINE_ITEMS = new HashSet<IMS_SHIPMENT_LINE_ITEMS>();
            this.IMS_SHIPMENT_CONTAINERS = new HashSet<IMS_SHIPMENT_CONTAINERS>();
        }
    
        public int ORIGREC { get; set; }
        public string ORIGSTS { get; set; }
        public int SHIPMENTID { get; set; }
        public string ASNNUMBER { get; set; }
        public Nullable<System.DateTime> ASNCREATIONDATE { get; set; }
        public string RECEIVESTATUS { get; set; }
        public Nullable<System.DateTime> SHIPMENTDATE { get; set; }
        public Nullable<System.DateTime> STATUSTIME { get; set; }
        public int CUSTOMERID { get; set; }
        public string HAS_SYSTEM_GENERATED_TAGS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_PO_SHIPMENTS> IMS_PO_SHIPMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_SHIPMENT_LINE_ITEMS> IMS_SHIPMENT_LINE_ITEMS { get; set; }
        public virtual IMS_SUPPLIER_CUSTOMERS IMS_SUPPLIER_CUSTOMERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_SHIPMENT_CONTAINERS> IMS_SHIPMENT_CONTAINERS { get; set; }
    }
}
