//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_SHIPMENT_CONTAINERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMS_SHIPMENT_CONTAINERS()
        {
            this.IMS_SHIPMENT_LINE_ITEMS = new HashSet<IMS_SHIPMENT_LINE_ITEMS>();
            this.IMS_SHIPMENT_ITEMS = new HashSet<IMS_SHIPMENT_ITEMS>();
        }
    
        public int ORIGREC { get; set; }
        public string ORIGSTS { get; set; }
        public int CONTAINERID { get; set; }
        public string CONTAINERTYPE { get; set; }
        public int SHIPMENTID { get; set; }
        public Nullable<int> PARENTCONTAINERID { get; set; }
        public string TAGREADSTATUS { get; set; }
        public Nullable<System.DateTime> TAGREADTIME { get; set; }
        public string SSCC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_SHIPMENT_LINE_ITEMS> IMS_SHIPMENT_LINE_ITEMS { get; set; }
        public virtual IMS_SHIPMENTS IMS_SHIPMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_SHIPMENT_ITEMS> IMS_SHIPMENT_ITEMS { get; set; }
    }
}
