//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_ITEMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMS_ITEMS()
        {
            this.IMS_SHIPMENT_ITEMS = new HashSet<IMS_SHIPMENT_ITEMS>();
        }
    
        public int ORIGREC { get; set; }
        public string ORIGSTS { get; set; }
        public int ITEMID { get; set; }
        public string SGTIN { get; set; }
        public Nullable<int> COSTCENTERID { get; set; }
        public string STATUS { get; set; }
        public System.DateTime STATUSTIME { get; set; }
        public string LOCATIONCODE { get; set; }
        public Nullable<System.DateTime> LOCATIONTIME { get; set; }
        public Nullable<int> ITEMLOTID { get; set; }
        public int PRODUCTID { get; set; }
        public string TAG_GTIN14 { get; set; }
        public string TAG_SN { get; set; }
        public Nullable<int> CONSUMPTION_UNITS { get; set; }
        public string SYSTEM_GENERATED_TAG { get; set; }
        public int QCSAMPLE { get; set; }
        public Nullable<System.DateTime> QCCHECKOUTTIME { get; set; }
        public string QUARANTINESTATUS { get; set; }
        public string CONSUMEREASON { get; set; }
        public string BARCODE_FLAG { get; set; }
        public Nullable<System.DateTime> RECEIPTTIME { get; set; }
    
        public virtual IMS_COST_CENTERS IMS_COST_CENTERS { get; set; }
        public virtual IMS_LOTS IMS_LOTS { get; set; }
        public virtual IMS_PRODUCTS IMS_PRODUCTS { get; set; }
        public virtual LOCATION LOCATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_SHIPMENT_ITEMS> IMS_SHIPMENT_ITEMS { get; set; }
    }
}
