//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_PHYSICALITEM_DIS_LOG
    {
        public int ORIGREC { get; set; }
        public string ORIGSTS { get; set; }
        public int PHYSICALINVENTORYID { get; set; }
        public string SGTIN { get; set; }
        public int PHYSICALITEMID { get; set; }
        public System.DateTime PROCESSED_TIME { get; set; }
        public string STATUS { get; set; }
    
        public virtual IMS_PHYSICAL_INVENTORY IMS_PHYSICAL_INVENTORY { get; set; }
        public virtual IMS_PHYSICAL_ITEMS IMS_PHYSICAL_ITEMS { get; set; }
    }
}
