//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_LOTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMS_LOTS()
        {
            this.IMS_ITEMS = new HashSet<IMS_ITEMS>();
        }
    
        public int ORIGREC { get; set; }
        public string ORIGSTS { get; set; }
        public int LOTID { get; set; }
        public string LOTNUMBER { get; set; }
        public Nullable<System.DateTime> LOTEXPIRATION { get; set; }
        public int PRODUCTID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_ITEMS> IMS_ITEMS { get; set; }
        public virtual IMS_PRODUCTS IMS_PRODUCTS { get; set; }
    }
}
