//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_PURPOSES
    {
        public int ORIGREC { get; set; }
        public string ORIGSTS { get; set; }
        public string USAGE_PURPOSE_CODE { get; set; }
        public string USAGE_PURPOSE_TEXT { get; set; }
        public int SORTER { get; set; }
    }
}
