//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_PHYSICAL_INVENTORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMS_PHYSICAL_INVENTORY()
        {
            this.IMS_PHYSICAL_ITEMS = new HashSet<IMS_PHYSICAL_ITEMS>();
            this.IMS_PHYSICALITEM_DIS_LOG = new HashSet<IMS_PHYSICALITEM_DIS_LOG>();
        }
    
        public int ORIGREC { get; set; }
        public string ORIGSTS { get; set; }
        public int PHYSICALINVENTORYID { get; set; }
        public System.DateTime START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string STATUS { get; set; }
        public string USRNAM { get; set; }
        public string LOCATION_NAME { get; set; }
        public Nullable<int> PHYSICALINVENTORYREVIEWID { get; set; }
        public string LOCATIONCODE { get; set; }
        public string LOCATION_SHORTNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_PHYSICAL_ITEMS> IMS_PHYSICAL_ITEMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_PHYSICALITEM_DIS_LOG> IMS_PHYSICALITEM_DIS_LOG { get; set; }
        public virtual IMS_PHYSICAL_INVENTORY_REV IMS_PHYSICAL_INVENTORY_REV { get; set; }
    }
}
