//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_PO_SHIPMENTS
    {
        public int ORIGREC { get; set; }
        public string ORIGSTS { get; set; }
        public int PURCHASEORDERID { get; set; }
        public int SHIPMENTID { get; set; }
    
        public virtual IMS_PURCHASE_ORDERS IMS_PURCHASE_ORDERS { get; set; }
        public virtual IMS_SHIPMENTS IMS_SHIPMENTS { get; set; }
    }
}
