//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_PO_LINE_ITEMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMS_PO_LINE_ITEMS()
        {
            this.IMS_SHIPMENT_LINE_ITEMS = new HashSet<IMS_SHIPMENT_LINE_ITEMS>();
        }
    
        public int ORIGREC { get; set; }
        public string ORIGSTS { get; set; }
        public int ORDERLINEITEMID { get; set; }
        public string LINE_ITEM_NUMBER { get; set; }
        public int QUANTITY_ORDERED { get; set; }
        public Nullable<int> QUANTITY_ACCEPTED { get; set; }
        public Nullable<int> QUANTITY_BACKORDERED { get; set; }
        public Nullable<int> QUANTITY_DELETED { get; set; }
        public Nullable<int> QUANTITY_SUBSTITUTED { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public string STATUS { get; set; }
        public System.DateTime STATUS_TIME { get; set; }
        public int PURCHASEORDERID { get; set; }
        public int PRODUCTID { get; set; }
        public Nullable<int> SUB_PRODUCTID { get; set; }
        public string SUB_COMMENT { get; set; }
        public string COMMENTS { get; set; }
        public int QUANTITY_PENDING { get; set; }
        public Nullable<int> QUANTITY_EXPECTED { get; set; }
        public Nullable<int> QUANTITY_RECEIVED { get; set; }
        public string ERP_PO_LINE_NUMBER { get; set; }
        public string ERP_PO_NUM { get; set; }
    
        public virtual IMS_PRODUCTS IMS_PRODUCTS { get; set; }
        public virtual IMS_PRODUCTS IMS_PRODUCTS1 { get; set; }
        public virtual IMS_PURCHASE_ORDERS IMS_PURCHASE_ORDERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_SHIPMENT_LINE_ITEMS> IMS_SHIPMENT_LINE_ITEMS { get; set; }
    }
}
