//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_SUPPLIER_CUSTOMERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMS_SUPPLIER_CUSTOMERS()
        {
            this.IMS_PURCHASE_ORDERS = new HashSet<IMS_PURCHASE_ORDERS>();
            this.IMS_SHIPMENTS = new HashSet<IMS_SHIPMENTS>();
        }
    
        public int ORIGREC { get; set; }
        public string ORIGSTS { get; set; }
        public int CUSTOMERID { get; set; }
        public string SHIP_TO_CUSTOMER_ID { get; set; }
        public string NAME { get; set; }
        public string SUPPCODE { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string POSTALCODE { get; set; }
        public string COUNTRYCODE { get; set; }
        public string ADDRESS_2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_PURCHASE_ORDERS> IMS_PURCHASE_ORDERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_SHIPMENTS> IMS_SHIPMENTS { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
