//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_PHYSICAL_ITEMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMS_PHYSICAL_ITEMS()
        {
            this.IMS_PHYSICALITEM_DIS_LOG = new HashSet<IMS_PHYSICALITEM_DIS_LOG>();
        }
    
        public int ORIGREC { get; set; }
        public string ORIGSTS { get; set; }
        public string SGTIN { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string SUPPLIER_NAME { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> STATUS_TIME { get; set; }
        public string LOTNUMBER { get; set; }
        public int PHYSICALINVENTORYID { get; set; }
        public Nullable<System.DateTime> LOTEXPIRATION { get; set; }
        public int PHYSICALITEMID { get; set; }
        public string DISPOSITION_STATUS { get; set; }
        public Nullable<System.DateTime> DISPOSITION_STATUS_TIME { get; set; }
        public string DISPOSITION_USRNAM { get; set; }
        public string TAG_GTIN14 { get; set; }
        public string TAG_SN { get; set; }
        public string DISPOSITION_PARM { get; set; }
        public string OVERRIDDEN { get; set; }
        public string NEWLOCATIONCODE { get; set; }
        public string DISCREPANCYNEWLOCATION { get; set; }
        public string PROCESSED { get; set; }
        public string DISCREPANCY { get; set; }
        public string SCAN_ITEM_STATUS { get; set; }
        public string PREVIOUS_LOCATION { get; set; }
        public string OVERRIDE_CODE { get; set; }
        public string DISPOSITION_CODE { get; set; }
        public Nullable<int> DISCREPANCY_CODE { get; set; }
        public string TEST_CODE { get; set; }
    
        public virtual IMS_PHYSICAL_INVENTORY IMS_PHYSICAL_INVENTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_PHYSICALITEM_DIS_LOG> IMS_PHYSICALITEM_DIS_LOG { get; set; }
    }
}
