//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_PURCHASE_ORDERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMS_PURCHASE_ORDERS()
        {
            this.IMS_PO_LINE_ITEMS = new HashSet<IMS_PO_LINE_ITEMS>();
            this.IMS_PO_SHIPMENTS = new HashSet<IMS_PO_SHIPMENTS>();
        }
    
        public int ORIGREC { get; set; }
        public string ORIGSTS { get; set; }
        public int PURCHASEORDERID { get; set; }
        public string PO_NUMBER { get; set; }
        public string PO_CUSTOMER_REF { get; set; }
        public string PO_SUPPLIER_REF { get; set; }
        public System.DateTime APPROVAL_DATE { get; set; }
        public Nullable<System.DateTime> CONFIRM_DATE { get; set; }
        public Nullable<System.DateTime> PROCESS_DATE { get; set; }
        public string STATUS { get; set; }
        public System.DateTime STATUS_TIME { get; set; }
        public int COST_CENTER_ID { get; set; }
        public int CUSTOMERID { get; set; }
        public Nullable<System.DateTime> REQ_SHIP_DATE { get; set; }
        public string TXSTATUS { get; set; }
        public System.DateTime TXSTATUS_TIME { get; set; }
        public string ACKSTATUS { get; set; }
        public Nullable<System.DateTime> ACKSTATUS_TIME { get; set; }
        public string ERP_PO_NUMBER { get; set; }
        public string ERP_KEY_DATA { get; set; }
    
        public virtual IMS_COST_CENTERS IMS_COST_CENTERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_PO_LINE_ITEMS> IMS_PO_LINE_ITEMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_PO_SHIPMENTS> IMS_PO_SHIPMENTS { get; set; }
        public virtual IMS_SUPPLIER_CUSTOMERS IMS_SUPPLIER_CUSTOMERS { get; set; }
    }
}
