//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_COST_CENTERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMS_COST_CENTERS()
        {
            this.IMS_ITEMS = new HashSet<IMS_ITEMS>();
            this.IMS_COST_CENTER_PRODUCTS = new HashSet<IMS_COST_CENTER_PRODUCTS>();
            this.IMS_PURCHASE_ORDERS = new HashSet<IMS_PURCHASE_ORDERS>();
        }
    
        public int ORIGREC { get; set; }
        public string ORIGSTS { get; set; }
        public int COST_CENTER_ID { get; set; }
        public string COST_CENTER_NAME { get; set; }
        public string COST_CENTER_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string DEPT { get; set; }
        public string COST_CENTER_FULLNAME { get; set; }
        public string INTRANSIT { get; set; }
        public string SHORTDESCRIPTION { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_ITEMS> IMS_ITEMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_COST_CENTER_PRODUCTS> IMS_COST_CENTER_PRODUCTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_PURCHASE_ORDERS> IMS_PURCHASE_ORDERS { get; set; }
    }
}
