//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIMSCOUNTER
    {
        public string TABLNAME { get; set; }
        public string PREFIX { get; set; }
        public string ORIGSTS { get; set; }
        public int ORIGREC { get; set; }
        public int LIMSCOUNTER1 { get; set; }
        public string FLDNAME { get; set; }
    }
}
