//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlinIQ_DataEntities : DbContext
    {
        public AlinIQ_DataEntities()
            : base("name=AlinIQ_DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BUILDING> BUILDINGS { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENTS { get; set; }
        public virtual DbSet<IMS_COST_CENTERS> IMS_COST_CENTERS { get; set; }
        public virtual DbSet<IMS_ITEMS> IMS_ITEMS { get; set; }
        public virtual DbSet<IMS_LOTS> IMS_LOTS { get; set; }
        public virtual DbSet<IMS_PHYSICAL_INVENTORY> IMS_PHYSICAL_INVENTORY { get; set; }
        public virtual DbSet<IMS_PHYSICAL_INVENTORY_REV> IMS_PHYSICAL_INVENTORY_REV { get; set; }
        public virtual DbSet<IMS_PHYSICAL_ITEMS> IMS_PHYSICAL_ITEMS { get; set; }
        public virtual DbSet<IMS_PHYSICALITEM_DIS_LOG> IMS_PHYSICALITEM_DIS_LOG { get; set; }
        public virtual DbSet<IMS_PRODUCTS> IMS_PRODUCTS { get; set; }
        public virtual DbSet<IMS_PURPOSES> IMS_PURPOSES { get; set; }
        public virtual DbSet<LOCATION> LOCATIONS { get; set; }
        public virtual DbSet<METADATA_LOOKUP_VALUES> METADATA_LOOKUP_VALUES { get; set; }
        public virtual DbSet<METADATA_LOOKUPS> METADATA_LOOKUPS { get; set; }
        public virtual DbSet<ROOM> ROOMS { get; set; }
        public virtual DbSet<SUPPLIER> SUPPLIERS { get; set; }
        public virtual DbSet<LIMSCOUNTER> LIMSCOUNTERS { get; set; }
        public virtual DbSet<X_TEST_RL> X_TEST_RL { get; set; }
        public virtual DbSet<IMS_COST_CENTER_PRODUCTS> IMS_COST_CENTER_PRODUCTS { get; set; }
        public virtual DbSet<IMS_PO_LINE_ITEMS> IMS_PO_LINE_ITEMS { get; set; }
        public virtual DbSet<IMS_PO_SHIPMENTS> IMS_PO_SHIPMENTS { get; set; }
        public virtual DbSet<IMS_PURCHASE_ORDERS> IMS_PURCHASE_ORDERS { get; set; }
        public virtual DbSet<IMS_SHIPMENT_ITEMS> IMS_SHIPMENT_ITEMS { get; set; }
        public virtual DbSet<IMS_SHIPMENT_LINE_ITEMS> IMS_SHIPMENT_LINE_ITEMS { get; set; }
        public virtual DbSet<IMS_SHIPMENTS> IMS_SHIPMENTS { get; set; }
        public virtual DbSet<IMS_SUPPLIER_CUSTOMERS> IMS_SUPPLIER_CUSTOMERS { get; set; }
        public virtual DbSet<IMS_SHIPMENT_CONTAINERS> IMS_SHIPMENT_CONTAINERS { get; set; }
    }
}
