//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROOM()
        {
            this.LOCATIONS = new HashSet<LOCATION>();
        }
    
        public string ROOM_NAME { get; set; }
        public int ROOM_ID { get; set; }
        public string ROOM_CODE { get; set; }
        public string ORIGSTS { get; set; }
        public int ORIGREC { get; set; }
        public string DESCRIPTION { get; set; }
        public int BUILDING_ID { get; set; }
    
        public virtual BUILDING BUILDING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCATION> LOCATIONS { get; set; }
    }
}
